import { describe, it, expect, beforeEach, afterEach } from 'vitest'
import { EventEmitter } from 'events'
import { AddressInfo } from 'net'
import { setupOAuthCallbackServerWithLongPoll } from './utils'
import { NodeOAuthClientProvider } from './node-oauth-client-provider'

/**
 * SEC-4 — OAuth callback does not validate `state`.
 *
 * Without a state check, any local process (or a web page that guesses the callback
 * port) can hit http://127.0.0.1:<port>/oauth/callback?code=<attacker_code> and have
 * mcp-remote exchange the attacker's authorization code, binding the session to the
 * attacker's account.
 */
describe('OAuth callback state validation (SEC-4)', () => {
  const EXPECTED_STATE = 'the-real-nonce'
  let server: any
  let port: number
  let events: EventEmitter

  const callback = (query: string) => fetch(`http://127.0.0.1:${port}/oauth/callback?${query}`)

  beforeEach(async () => {
    events = new EventEmitter()
    const result = setupOAuthCallbackServerWithLongPoll({
      port: 0,
      path: '/oauth/callback',
      events,
      expectedState: EXPECTED_STATE,
    })
    server = result.server
    await new Promise<void>((resolve) => server.on('listening', () => resolve()))
    port = (server.address() as AddressInfo).port
  })

  afterEach(() => {
    server?.close()
    server = null
  })

  it('rejects a callback carrying no state at all', async () => {
    // Given an attacker who knows the callback port but not the nonce
    // When they inject an authorization code with no state
    const res = await callback('code=attacker_code')

    // Then the code is refused
    expect(res.status).toBe(400)
    expect(await res.text()).toContain('invalid state')
  })

  it('rejects a callback whose state does not match', async () => {
    // Given an attacker guessing at the nonce
    // When they inject an authorization code with the wrong state
    const res = await callback('code=attacker_code&state=guessed-wrong')

    // Then the code is refused
    expect(res.status).toBe(400)
    expect(await res.text()).toContain('invalid state')
  })

  it('accepts the callback from the real authorization server', async () => {
    // Given the authorization server redirecting back with the nonce we issued
    // When the callback arrives
    const res = await callback(`code=legitimate_code&state=${EXPECTED_STATE}`)

    // Then the flow proceeds as normal
    expect(res.status).toBe(200)
    expect(await res.text()).toContain('Authorization successful')
  })

  it('does not resolve the auth-code promise for a rejected callback', async () => {
    // Given a pending auth flow
    const { waitForAuthCode } = setupOAuthCallbackServerWithLongPoll({
      port: 0,
      path: '/oauth/callback',
      events,
      expectedState: EXPECTED_STATE,
    })
    const pending = waitForAuthCode()
    const sentinel = Symbol('still-pending')

    // When an attacker's code is rejected on the first server
    await callback('code=attacker_code&state=wrong')

    // Then no authorization code was ever handed to the OAuth flow
    const winner = await Promise.race([pending, Promise.resolve(sentinel)])
    expect(winner).toBe(sentinel)
  })
})

describe('OAuth provider state nonce (SEC-4)', () => {
  it('sends the same nonce the callback server is validating against', () => {
    // Given a nonce generated by the entrypoint and handed to both halves of the flow
    const provider = new NodeOAuthClientProvider({
      serverUrl: 'https://example.com',
      callbackPort: 8080,
      host: 'localhost',
      serverUrlHash: 'test-hash',
      state: 'shared-nonce',
    })

    // When the provider reports the state it will put on the authorization request
    // Then it is the nonce the callback will check, not an unrelated one
    expect(provider.state()).toBe('shared-nonce')
  })

  it('still generates a nonce when none is supplied', () => {
    // Given standalone use with no shared nonce
    const provider = new NodeOAuthClientProvider({
      serverUrl: 'https://example.com',
      callbackPort: 8080,
      host: 'localhost',
      serverUrlHash: 'test-hash',
    })

    // Then a state is still sent, preserving the previous behaviour
    expect(provider.state()).toBeTruthy()
  })
})
